=== orax-Astroneer-mods/BetterCanistersMod/resources/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "minLength": 1,
      "type": "string"
    },
    "author": {
      "description": "The name of the mod creator.",
      "minLength": 1,
      "type": "string"
    },
    "canonical_name": {
      "description": "The canonical name.",
      "minLength": 1,
      "type": "string"
    },
    "description": {
      "description": "A detailed description of the mod's features.",
      "minLength": 1,
      "type": "string"
    },
    "homepage": {
      "description": "The URL to the mod page (e.g., Nexus Mods or GitHub).",
      "format": "uri",
      "minLength": 1,
      "type": "string"
    },
    "name": {
      "description": "The display name of the mod as seen by users.",
      "minLength": 1,
      "type": "string"
    }
  },
  "required": [
    "canonical_name",
    "name"
  ],
  "title": "Mod metadata schema",
  "type": "object"
}

=== orax-Astroneer-mods/BetterCanistersMod/mod.json
{
    "$schema": "./resources/schema.json",
    "author": "orax",
    "canonical_name": "BetterCanisters",
    "description": "Customize the capacity and transfer rate of canisters and oxygen tanks.",
    "homepage": "https://www.nexusmods.com/profile/0R4X/mods?gameId=1955",
    "name": "Better Canisters"
}
